### ISSUE TITLE
lean.sh appears in Java/scripts scripts upon being downloaded by other projects.

### ISSUE THREAD

**Issue by Nic0Nic0Nii** [sigonasr2/SigScript#1]
And we don't know why...

**Comment by Nic0Nic0Nii** [comment]
It is obvious that it gets the name from `clean.sh` and just chops off the letter c, but why...?

**Comment by sigonasr2** [comment]
Refactoring the code quite a bit, to include a new `LANGUAGE` parameter has cleared this bug.
